DISTRO_NAME = "compute"

VIRTUAL-RUNTIME_init_manager = "systemd"

PREFERRED_VERSION_libglvnd = "1.4.0"

VIRTUAL-RUNTIME_wpa-supplicant = ""

DISTRO_FEATURES:append = " systemd networkmanager wifi opengl"