BBPATH:prepend := "${LAYERDIR}:"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-product"
BBFILE_PATTERN_meta-product = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-product = "6"

LAYERDEPENDS_meta-product = "core"
LAYERSERIES_COMPAT_meta-product = "kirkstone"